name: Sync test

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository A
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        # 리포 A를 체크아웃합니다.

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        # Git 설정을 합니다. 푸시를 할 사용자 정보를 설정합니다.

    - name: Clone personal repository
      run: |
        mkdir temp_folder
        cd temp_folder
        git clone https://github.com/young2good/leetcode.git
        # 리포 A를 클론합니다. 디렉토리를 생성하고 클론합니다.

    - name: Commit and push changes to repository B
      run: |
        cd temp_folder/leetcode
        git add .
        git commit -m "Sync changes from repository A"
        git push https://young2good:${{ secrets.PAT }}@github.com/young2good/yh_temp.git main
        # 리포 B의 변경사항을 커밋하고 푸시합니다. PAT을 사용하여 인증합니다.
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Clean up
      run: |
        rm -rf temp_folder
        # 클론된 디렉토리를 삭제하여 클린업합니다.
