name: Sync test

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Add remote repository
      run: |
        git remote add target https://young2good:${{ secrets.PAT }}@github.com/young2good/yh_temp.git

    - name: Push changes to organization repository
      run: |
        git push target main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
