name: Sync test

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Add remote repository
      run: |
        git remote add target https://young2good:${{ secrets.PAT }}@github.com/young2good/yh_temp.git

    - name: Check for changes
      id: check_changes
      run: |
        if git diff --cached --quiet; then
          echo "No changes to commit"
          exit 1
        fi

    - name: Add changes to git
      if: steps.check_changes.outcome == 'success'
      run: |
        git add .

    - name: Commit changes
      if: steps.check_changes.outcome == 'success'
      run: |
        git commit -m "Sync changes from repo A"

    - name: Push changes to organization repository
      if: steps.check_changes.outcome == 'success'
      run: |
        git push target main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
